#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Lib.KingJA.SwitchButton.Resource", IsApplication=false)]

namespace Lib.KingJA.SwitchButton
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public static int selectedColor = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int selectedTab = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int strokeRadius = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int strokeWidth = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int switchTabs = 2130771973;
			
			// aapt resource value: 0x7f010002
			public static int textSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int app_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SwitchMultiButton = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 4
			public static int SwitchMultiButton_selectedColor = 4;
			
			// aapt resource value: 3
			public static int SwitchMultiButton_selectedTab = 3;
			
			// aapt resource value: 0
			public static int SwitchMultiButton_strokeRadius = 0;
			
			// aapt resource value: 1
			public static int SwitchMultiButton_strokeWidth = 1;
			
			// aapt resource value: 5
			public static int SwitchMultiButton_switchTabs = 5;
			
			// aapt resource value: 2
			public static int SwitchMultiButton_textSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
